- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: latest

- name: Enable rate-limiting on ssh
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow ssh port
  community.general.ufw:
    rule: allow
    port: "{{ ansible_port }}"

- name: Allow 443
  community.general.ufw:
    rule: allow
    port: 443

- name: Enable and deny by default
  community.general.ufw:
    state: enabled
    default: deny
